# Collector specific configuration
base_url: "https://goadmin.ifrc.org/api/v2/"
get_params: "/?limit=200&format=json"

countries:
  url_path: "country"
  filename: "countries_{index}.json"

appeals:
  publish: True
  url_path: "appeal"
  additional_params: "&appeal__real_data_update__gte="
  filename: "appeals_{index}.json"
  heading: "Appeals"
  tags:
    - "funding"
  showcase_urls:
    global: "https://go.ifrc.org/"

whowhatwhere:
  publish: False
  url_path: "project"
  additional_params: "&modified_at__gte="
  filename: "whowhatwhere_{index}.json"
  heading: "3W"
  tags:
    - "who is doing what and where-3w-4w-5w"
  showcase_urls:
    global: "https://go.ifrc.org/three-w/"
    country: "https://go.ifrc.org/countries/{id}#3w"
